### ISSUE TITLE
How to Upgrade to Version 2.X?

### ISSUE THREAD

**Issue by Schneidertm** [megoesrawr/Modern-LWC#102]
Sorry for posting here but sadly I didn't find any future information and no one is responding on the spigotmc thread: How to upgrade to version 2.X? I did search everywhere without success. I did try to just upgrade the .jar as usually but my mysql database didn't upgrade and anything way unprotected.

Would love to know how to upgrade the database or the plugin at all

**Comment by megoesrawr** [comment]
It should just be a drop-in update.

**Comment by mrcoffee1026** [comment]
Upgrading doesn't work as I and several others have already reported.  The new version records two lines in the database per lock whereas the previous version correctly only put one line into the database per lock.  Since the new version seems to expect both lines to be present for every lock, every lock prior to the new version fails to work, although will still take up space in the database and cannot be accessed.

You can "upgrade" in the current state by wiping the database and placing the new version... or leaving the old locks in the database as they'll just be ignored.  I would expect that EVENTUALLY they will deal with the issue of every new lock hogging two rows of database space for one row of data... at which point an upgrade will be possible.  Until then, all you can do is re-lock everything as if you haven't had the plugin... knowing that you'll very likely have to wipe the new locks out at some point in the future when they fix the issue.

**Comment by Tsuser1** [comment]
Fixed in 2.1.x builds when they are published.

**Issue closed.**
